// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-I_sGmnx9v2cPHkmqde6fui_xWPOLYo',
    appId: '1:478953432459:web:e724ba27ecc1187442bb8e',
    messagingSenderId: '478953432459',
    projectId: 'push-notification-demo-89ab4',
    authDomain: 'push-notification-demo-89ab4.firebaseapp.com',
    storageBucket: 'push-notification-demo-89ab4.appspot.com',
    measurementId: 'G-F5XZ6ZKS7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiqv6KFHxdo8qyWf6s1gBsSFKh0YBV9p8',
    appId: '1:478953432459:android:e2011164ea69465c42bb8e',
    messagingSenderId: '478953432459',
    projectId: 'push-notification-demo-89ab4',
    storageBucket: 'push-notification-demo-89ab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFBAs3dzasz7Po9mqEiHC9hardZLStLyo',
    appId: '1:478953432459:ios:c5b79c231b17913042bb8e',
    messagingSenderId: '478953432459',
    projectId: 'push-notification-demo-89ab4',
    storageBucket: 'push-notification-demo-89ab4.appspot.com',
    iosClientId: '478953432459-t6rrofstd44vdnd2aitvdodbmi8rnp3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFBAs3dzasz7Po9mqEiHC9hardZLStLyo',
    appId: '1:478953432459:ios:c5b79c231b17913042bb8e',
    messagingSenderId: '478953432459',
    projectId: 'push-notification-demo-89ab4',
    storageBucket: 'push-notification-demo-89ab4.appspot.com',
    iosClientId: '478953432459-t6rrofstd44vdnd2aitvdodbmi8rnp3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotification',
  );
}
